### ISSUE TITLE
Suggestion: Make a real-size preview

### ISSUE THREAD

**Issue by Lxtharia** [gianklug/millitext#1]
Hi, nice working website, only thing I was missing is a (live) preview of the actual image so I don't have to download it every time to see the real effect on my screen. 

Thanks, have a nice day!

**Comment by gianklug** [comment]
Hey there, thanks for the suggestion!

Implemented in https://github.com/gianklug/millitext/commit/12d3892369d6b3426c4dba10da8b2d3f07b2eb2f and now live on https://millitext.gk.wtf/ :D

**Comment by Lxtharia** [comment]
That was quick! Thank you very much :D
